controls/V-72433.rb

Signed-off-by: Noel Georgi <noel.georgi@reancloud.com>

Fixing typo with OCSP name

---

controls/V-71999.rb
libraries/linux_updates.rb

The added linux_updates resource was written last year by the InSpec crew at Chef.
We may want to consider pushing the resource up a level since it's applicable to multiple linux platforms if it doesn't get added to InSpec core.

Added linux updates resource and test for V-71999

---

controls/V-71973.rb
controls/V-72073.rb

Added:
V-71973
Modified:
V-72063

File Integrity Tool Control Updates

---

controls/V-72035.rb
controls/V-72043.rb
controls/V-72045.rb
controls/V-72311.rb
controls/V-73161.rb

Updated controls that used etc_fstab in order to properly take advantage of the resource.

Changed controls using etc_fstab to work properly with resource

---

controls/V-71903.rb
controls/V-71905.rb
controls/V-71907.rb
controls/V-71909.rb
controls/V-71911.rb
controls/V-71913.rb
controls/V-71915.rb
controls/V-71917.rb
controls/V-71935.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to pwquality controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for pwquality controls

---

controls/V-71953.rb
controls/V-71955.rb
controls/V-71993.rb
controls/V-77823.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to gnome controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for gnome controls

---

controls/V-71971.rb
controls/V-71989.rb
controls/V-71991.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to selinux controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for selinux controls rev4

---

controls/V-71919.rb
controls/V-71933.rb
controls/V-71937.rb
controls/V-71943.rb
controls/V-71945.rb
controls/V-72245.rb
controls/V-72275.rb
controls/V-73159.rb
libraries/matchers.rb
libraries/pam.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to PAM controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for PAM controls

---

controls/V-71939.rb
controls/V-71957.rb
controls/V-71959.rb
controls/V-72221.rb
controls/V-72233.rb
controls/V-72235.rb
controls/V-72237.rb
controls/V-72239.rb
controls/V-72241.rb
controls/V-72243.rb
controls/V-72247.rb
controls/V-72249.rb
controls/V-72251.rb
controls/V-72253.rb
controls/V-72255.rb
controls/V-72257.rb
controls/V-72259.rb
controls/V-72261.rb
controls/V-72263.rb
controls/V-72265.rb
controls/V-72267.rb
controls/V-72303.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to ssh controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for ssh controls

---

controls/V-71921.rb
controls/V-71925.rb
controls/V-71927.rb
controls/V-71929.rb
controls/V-71931.rb
controls/V-71951.rb
controls/V-71995.rb
controls/V-72013.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to login_defs controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for login_defs controls

---

controls/V-72213.rb
controls/V-72215.rb

These are all the changes we have made in our repo at https://github.com/djhaynes/inspec-profile-disa_stig-el7 relating to antivirus controls. This includes updates of these controls to RHEL7 STIG Rev4, as well as various fixes.

Fixes and Rev4 updates for antivirus controls

---

attributes.yml
controls/V-71861.rb
controls/V-71863.rb
controls/V-71911.rb
controls/V-71935.rb
controls/V-71941.rb
controls/V-71965.rb
controls/V-72001.rb
controls/V-72011.rb
controls/V-72015.rb
controls/V-72017.rb
controls/V-72019.rb
controls/V-72021.rb
controls/V-72023.rb
controls/V-72025.rb
controls/V-72043.rb
controls/V-72059.rb
controls/V-72225.rb
controls/V-72237.rb
controls/V-72317.rb
controls/V-72417.rb
controls/V-72433.rb
controls/V-77819.rb

Adding an attributes.yml which contains all the default values for all the attributes.  Also went through and cleaned up all the attributes, making sure the defaults are all consistent, for example.

Add attributes file and clean attributes

---

controls/V-72027.rb

Updated the find command for V-72027 to filter by 'type -f'

---

attributes.yml

Update mfa_pkg_list attribute with packages from RHEL documentation

---

attributes.yml
controls/V-72039.rb
controls/V-72241.rb
controls/V-72251.rb
controls/V-72305.rb

This pull request closes #48 and fixes the `TODO` in `controls/V-72039.rb#56`. Beyond that:
* I've updated and expanded comments in the `attributes.yml` 
* Check for the RedHat release per the STIG for V-72241 and V-72251.

Various updates

---

controls/V-71973.rb
controls/V-71975.rb
controls/V-72069.rb
controls/V-72071.rb
controls/V-72073.rb

Added the subsystem tag to all controls that test aide

Added subsystem tag to aide tests

---

controls/V-71953.rb
controls/V-71955.rb
controls/V-71977.rb
controls/V-71979.rb
controls/V-71981.rb
controls/V-72001.rb
controls/V-72027.rb
controls/V-72089.rb

Updating controls to use resources so they work with InSpec v4.18.

updating controls to use resources.

---

controls/V-72315.rb

This PR is associated with PR #8.

Adding an automated test for this control. 

---

controls/V-72219.rb

@trevor-vaughan I took a pass at this and wrote the check so it checks all zones rather than just the default. This is part of PR #8.

Updating control to check ports and services for all zones.

---

inputs.nolong.yml.example
inputs.yml.example
inspec.yml

Updating attributes to inputs and moving defaults to inspec.yml.

---

CHANGELOG
controls/V-71971.rb

- Fixed the SELinux tests to ignore system_u by default in V-71971

V-71971 SELinux should ignore system_u

---

inspec.yml

Modified a duplicate declaration of 'file_integrity_tool' in inspec.yml.
Signed-off-by: Lesley Kimmel <lesley.j.kimmel@users.noreply.github.com>

Addressing issue #143

---

controls/V-72191.rb

Updated control V-72191 to reference '/usr/bin/kmod' instead of
'/sbin/insmod'.
Signed-off-by: Lesley Kimmel <lesley.j.kimmel@users.noreply.github.com>

Addressing issue #145
